l=list(range(21))
print(l[:5])
print(l[-5:])
print(l[1:11:2])
print(l[::5])
print(l[::])
print(l[::-1])
print('hello world'[0:7])
print('hello world'[0:-3])
ll=list("hello world")
print(ll[:7])